"""
analysis/screening/scoring_config.py
-------------------------------------
Approved scoring map for Phase 2 ranking (secondary type fit, land-use
penalty tags, and flood risk severity). Verbatim from costar_screener's
scoring_config.py -- see scoring_generator.py in the original project for
how new values get classified for a new market's CoStar export.
"""

SCORING_MAP = {
  "secondary_type_scores": {
    "Agricultural": 60,
    "Commercial": 80,
    "Industrial": 85,
    "Residential": 80
  },
  "land_use_penalty_tags": {
    "Agribusiness": 10,
    "Agricultural": 5,
    "Airplane Hangar": 30,
    "Airport": 40,
    "Amusement Park": 55,
    "Apartment Units": 10,
    "Apartment Units - Condo": 15,
    "Apartment Units - Dorms": 15,
    "Apartment Units - Senior": 15,
    "Apartment Units - Subsdzd": 15,
    "Auto Dealership": 75,
    "Auto Repair": 65,
    "Auto Salvage Facility": 50,
    "Bank": 90,
    "Bar": 70,
    "Baseball Field": 30,
    "Bowling Alley": 60,
    "Car Wash": 95,
    "Casino": 60,
    "Cement/Gravel Plant": 35,
    "Cemetery/Mausoleum": 55,
    "Chemical/Oil Refinery": 45,
    "Commercial": 10,
    "Community Center": 35,
    "Contractor Storage Yard": 15,
    "Convenience Store": 85,
    "Correctional Facility": 45,
    "Day Care Center": 65,
    "Department Store": 85,
    "Distribution": 5,
    "Drug Store": 85,
    "Fast Food": 95,
    "Food Processing": 30,
    "Funeral Home": 65,
    "Garden Center": 60,
    "General Freestanding": 50,
    "Golf Course/Driving Range": 45,
    "Health Care": 55,
    "Health Club": 60,
    "Hold for Development": 0,
    "Hold for Investment": 0,
    "Horse Stables": 20,
    "Hospital": 55,
    "Hospitality": 70,
    "Hotel": 80,
    "Industrial": 0,
    "Industrial Live/Work Unit": 5,
    "Industrial Park": 0,
    "Landfill": 50,
    "Lodge/Meeting Hall": 50,
    "Loft/Creative Space": 20,
    "Lumberyard": 30,
    "Manuftrd Hms/Mobl Hm Prk": 40,
    "Marina": 45,
    "Master Planned Community": 0,
    "Medical": 55,
    "Mixed Use": 10,
    "Motel": 80,
    "Movie Theater": 70,
    "MultiFamily": 5,
    "Neighborhood Center": 70,
    "Office": 45,
    "Office Park": 35,
    "Open Space": 10,
    "Parking Garage": 60,
    "Parking Lot": 55,
    "Pasture/Ranch": 5,
    "Planned Unit Development": 0,
    "Police/Fire Station": 50,
    "R&D": 15,
    "Rehabilitation Center": 45,
    "Religious Facility": 50,
    "Restaurant": 90,
    "Retail": 85,
    "Retail Warehouse": 50,
    "Schools": 45,
    "Self-Storage": 40,
    "Service Station": 90,
    "Shelter": 40,
    "Shipyard": 40,
    "Single Family Development": 0,
    "Single Family Residence": 10,
    "Spclty/Festvl/Entertnmnt": 65,
    "Storefrnt Retail/Residntl": 70,
    "Storefront": 75,
    "Storefront Retail/Office": 70,
    "Strip Center": 85,
    "Supermarket": 85,
    "Theater/Concert Hall": 65,
    "Timberland": 15,
    "Trailer/Camper Park": 40,
    "Truck Stop": 75,
    "Truck Terminal": 20,
    "Unknown": 0,
    "Utility Sub-Station": 45,
    "Veterinarian/Kennel": 55,
    "Warehouse": 10,
    "Water Retention Facility": 35,
    "Water Treatment Facility": 35,
    "Winery/Vineyard": 25
  },
  "flood_risk_scores": {
    "High Risk Areas": 10,
    "Moderate to Low Risk Areas": 75,
    "Undetermined Risk Areas": 40
  }
}
